# Week 2 Assignment

## Part 1 - NumPy

In [1]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d[:5])  # Display first 5 rows


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### 1. Define A and B and stack them vertically and horizontally

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

v_stack = np.vstack((A, B))
h_stack = np.hstack((A, B))

print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


### 2. Find common elements between A and B

In [3]:
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)


Common Elements: []


### 3. Extract numbers in A between 2 and 6

In [4]:
filtered_A = A[(A > 2) & (A < 6)]
print("Filtered A:", filtered_A)


Filtered A: [3 4]


### 4. Filter iris_2d with petallength > 1.5 and sepallength < 5.0

In [5]:
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Rows:\n", filtered_rows[:5])  # Print first 5 for brevity


Filtered Rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]]


## Part 2 - Pandas

In [6]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


### 1. Filter 'Manufacturer', 'Model' and 'Type' for every 20th row

In [7]:
df_20th = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(df_20th)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


### 2. Replace missing values in Min.Price and Max.Price

In [8]:
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print(df[['Min.Price', 'Max.Price']].head())


   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


<ipython-input-8-0304232d00c7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
<ipython-input-8-0304232d00c7>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)'

### 3. Get rows of dataframe where row sum > 100

In [9]:
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rows_gt_100 = df_random[df_random.sum(axis=1) > 100]
print(rows_gt_100)


     0   1   2   3
0   35  15  23  34
3   37  26  18  23
4   29  38  35  24
12  38  17  28  37
13  15  39  36  32
14  31  16  27  38
